# Einstieg Pandas
große Datensätze analysieren mit Pandas

# Was ist Pandas?

- Bibliothek auf Basis von NumPy
- Stellt Datenstrukturen und Tools zur Analyse großer Datenmengen zur Verfügung
- Vorteile ggü. Arbeit mit Excel
    - deutlich performanter
    - Open Source, große Community

# Datenstrukturen in Pandas
- Pandas arbeitet mit 2 Datenstrukturen: `Series` und `DataFrames`
    - `Series`: 1-dimensional mit Label (vgl. Excel-Spalte/Zeile)
    - `DataFrames`: 2-dimensional mit N Spalten (vgl. Excel-Tabelle)

# Daten in Pandas importieren

- Pandas bietet Funktionen um die meisten Datenformate zu importieren
    - Heute: .csv-Daten mithilfe von `read_csv(pfad-zur-datei)

In [18]:
import pandas
csv_daten = pandas.read_csv('../datasets/kundendaten_mock.csv')
csv_daten.head()

,Unnamed: 0,id,Vorname,Nachname,Email,Geschlecht,Alter
0,0,1,Owen,Lambol,olambol0@oaic.gov.au,M,29
1,1,2,Cullin,Goodwell,cgoodwell1@shinystat.com,M,63
2,2,3,Weber,Majury,wmajury2@techcrunch.com,M,12
3,3,4,Felipe,Prendergrast,fprendergrast3@hostgator.com,M,21
4,4,5,Helyn,Frounks,hfrounks4@123-reg.co.uk,F,31

# Einen Überblick verschaffen

*Hinweis: df steht hier für jeweils einen DataFrame etwa df = read.csv()..*
- `df.head(n)` zeigt die ersten n Zeilen eines DataFrames an, analog `df.tail(n)`
- `df.sample(n)` Stichprobe der Größe n entnehmen
- `df.sort_values(by=)` sortiert Tabelle nach gegebener Spalte
- `df.describe()` zeigt verschiedene Statistiken (Median, usw.) zu den Daten an

In [14]:
# csv_daten.head(10)
# csv_daten.tail(10)
# csv_daten.sort_values(by='Alter')
print(csv_daten.describe())
csv_daten.sample(n=20)

       Unnamed: 0          id       Alter
count  100.000000  100.000000  100.000000
mean    49.500000   50.500000   43.290000
std     29.011492   29.011492   19.427303
min      0.000000    1.000000  -14.000000
25%     24.750000   25.750000   28.000000
50%     49.500000   50.500000   41.000000
75%     74.250000   75.250000   58.000000
max     99.000000  100.000000   90.000000

,Unnamed: 0,id,Vorname,Nachname,Email,Geschlecht,Alter
80,80,81,Rudie,Froud,rfroud28@barnesandnoble.com,M,11
60,60,61,Kalila,Devon,kdevon1o@cmu.edu,F,40
18,18,19,Borg,Feedome,bfeedomei@arstechnica.com,M,62
37,37,38,Arliene,Poupard,apoupard11@digg.com,F,22
36,36,37,Evvie,Benez,ebenez10@cmu.edu,F,38
3,3,4,Felipe,Prendergrast,fprendergrast3@hostgator.com,M,21
53,53,54,Temple,Bucklan,tbucklan1h@nbcnews.com,M,58
50,50,51,Margy,Ziemen,mziemen1e@youtu.be,F,32
27,27,28,Ivor,McDavitt,imcdavittr@harvard.edu,M,61
77,77,78,Nathan,Carson,ncarson25@vk.com,M,46
35,35,36,Lurline,Harriman,lharrimanz@ucla.edu,F,41
68,68,69,Tomkin,Samter,tsamter1w@miibeian.gov.cn,M,70
93,93,94,Bealle,Shearsby,bshearsby2l@com.com,M,27
88,88,89,Sidonia,Gilgryst,sgilgryst2g@clickbank.net,F,27
71,71,72,Alicia,Huckin,ahuckin1z@jalbum.net,F,24
99,99,100,Blondell,Meins,bmeins2r@gravatar.com,F,51
98,98,99,Blondie,Wallenger,bwallenger2q@i2i.jp,F,56
75,75,76,Abbot,Flecknell,aflecknell23@ca.gov,M,40
24,24,25,Karoly,Spelsbury,kspelsburyo@flavors.me,M,43
49,49,50,Fabien,Vittle,fvittle1d@bravesites.com,M,31

# Daten selektieren

- nach Zeile `df.loc[1]` bzw. Abschnitt `df.loc[:10]`
- nach Spalte `df['Alter']` bzw. `df['Alter'][10:50]`
- nach Eigenschaften `df[df['Geschlecht'] == M` oder `df.query()`

In [15]:
#csv_daten.loc[10]
#csv_daten.loc[:10]
#csv_daten['Alter'][10:50]
#csv_daten['Email'].sample(10)
#csv_daten[csv_daten['Geschlecht'] == 'M']
csv_daten.query("Alter > 20")

,Unnamed: 0,id,Vorname,Nachname,Email,Geschlecht,Alter
0,0,1,Owen,Lambol,olambol0@oaic.gov.au,M,29
1,1,2,Cullin,Goodwell,cgoodwell1@shinystat.com,M,63
3,3,4,Felipe,Prendergrast,fprendergrast3@hostgator.com,M,21
4,4,5,Helyn,Frounks,hfrounks4@123-reg.co.uk,F,31
5,5,6,Ode,Lambal,olambal5@unblog.fr,M,36
6,6,7,Estell,Grandison,egrandison6@sciencedaily.com,F,41
7,7,8,Jodee,Sulman,jsulman7@oracle.com,F,55
8,8,9,Graig,McPhater,gmcphater8@ucoz.ru,M,51
9,9,10,Tammy,Faraday,tfaraday9@1und1.de,F,59
11,11,12,Thorvald,Cobbing,tcobbingb@angelfire.com,M,64
12,12,13,Etienne,Pasquale,epasqualec@rambler.ru,M,34
13,13,14,Marji,Camerana,mcameranad@bloglovin.com,F,83
14,14,15,Dorisa,Knyvett,dknyvette@4shared.com,F,50
15,15,16,Wait,Guess,wguessf@domainmarket.com,M,90
16,16,17,Lynne,Keedwell,lkeedwellg@biblegateway.com,F,28
17,17,18,Ermin,Kennally,ekennallyh@blogspot.com,M,73
18,18,19,Borg,Feedome,bfeedomei@arstechnica.com,M,62
19,19,20,Bogey,Penburton,bpenburtonj@home.pl,M,54
20,20,21,Eduard,Truse,etrusek@com.com,M,62
21,21,22,Kasper,Verchambre,kverchambrel@scientificamerican.com,M,55
22,22,23,Jeramey,Kegan,jkeganm@tripod.com,M,34
23,23,24,Terrijo,MacGilrewy,tmacgilrewyn@yelp.com,F,42
24,24,25,Karoly,Spelsbury,kspelsburyo@flavors.me,M,43
25,25,26,Elia,Coulman,ecoulmanp@reuters.com,M,61
26,26,27,Madelin,Frankcomb,mfrankcombq@cargocollective.com,F,69
27,27,28,Ivor,McDavitt,imcdavittr@harvard.edu,M,61
28,28,29,Celine,Colpus,ccolpuss@gnu.org,F,38
29,29,30,Roderich,Ellgood,rellgoodt@telegraph.co.uk,M,58
30,30,31,Court,Iggulden,cigguldenu@msu.edu,M,25
31,31,32,Tadeo,Scowcraft,tscowcraftv@virginia.edu,M,75
...,...,...,...,...,...,...,...
68,68,69,Tomkin,Samter,tsamter1w@miibeian.gov.cn,M,70
69,69,70,Lizbeth,Vannoort,lvannoort1x@flickr.com,F,27
70,70,71,Dario,Massard,dmassard1y@gnu.org,M,75
71,71,72,Alicia,Huckin,ahuckin1z@jalbum.net,F,24
72,72,73,Bea,Parfrey,bparfrey20@wordpress.org,F,25
73,73,74,Rudiger,Bircher,rbircher21@hibu.com,M,66
74,74,75,Caye,Gillyett,cgillyett22@pen.io,F,33
75,75,76,Abbot,Flecknell,aflecknell23@ca.gov,M,40
76,76,77,Lalo,Riccardini,lriccardini24@utexas.edu,M,28
77,77,78,Nathan,Carson,ncarson25@vk.com,M,46
78,78,79,Stacee,Mullenger,smullenger26@facebook.com,F,37
79,79,80,Pearline,Deverose,pdeverose27@spotify.com,F,39
81,81,82,Haleigh,Huyge,hhuyge29@123-reg.co.uk,F,63
83,83,84,Robena,Thomazet,rthomazet2b@opera.com,F,21
84,84,85,Derby,Hingeley,dhingeley2c@alexa.com,M,43
85,85,86,Mireille,Scothorn,mscothorn2d@toplist.cz,F,38
86,86,87,Cherin,Bariball,cbariball2e@webnode.com,F,65
87,87,88,Lazar,Ealles,lealles2f@about.com,M,25
88,88,89,Sidonia,Gilgryst,sgilgryst2g@clickbank.net,F,27
89,89,90,Abby,Pietruszewicz,apietruszewicz2h@over-blog.com,F,22
90,90,91,Ardis,Winchcum,awinchcum2i@dropbox.com,F,28
91,91,92,Gibb,Folkes,gfolkes2j@youku.com,M,29
92,92,93,Prent,Hutchins,phutchins2k@ustream.tv,M,61
93,93,94,Bealle,Shearsby,bshearsby2l@com.com,M,27
94,94,95,Milly,O' Quirk,moquirk2m@phpbb.com,F,39
95,95,96,Cacilie,Talks,ctalks2n@w3.org,F,33
96,96,97,Merrel,Tucsell,mtucsell2o@google.nl,M,87
97,97,98,Iris,Bountiff,ibountiff2p@nymag.com,F,40
98,98,99,Blondie,Wallenger,bwallenger2q@i2i.jp,F,56
99,99,100,Blondell,Meins,bmeins2r@gravatar.com,F,51

# Abschlussaufgabe: Explorativ Datensätze analysieren

- Als Abschlussaufgabe für den heutigen Tag haben wir 2 Datensätze vorbereitet
    - "Wine review"-Datensatz
    - Kickstarter-Datensatz
- Entnommen von der Plattform [Kaggle](https://www.kaggle.com/)
    - [https://www.kaggle.com/kemical/kickstarter-projects](https://www.kaggle.com/kemical/kickstarter-projects)
    - [https://www.kaggle.com/zynicide/wine-reviews](https://www.kaggle.com/zynicide/wine-reviews)

# Kickstarter-Datensatz

- Crowdfunding-Plattform [Kickstarter]()
- ~300.000 Datensätze zu Kickstarterprojekten
- Metadaten wie:
    - Projektname
    - Projektkategorie
    - erfragte Summe

In [19]:
import pandas
kickstarter = pandas.read_csv(r'../datasets/kickstarter-projects/ks-projects-201801.csv')
kickstarter.head().transpose()

,0,1,2,3,4
ID,1000002330,1000003930,1000004038,1000007540,1000011046
name,The Songs of Adelaide & Abullah,Greeting From Earth: ZGAC Arts Capsule For ET,Where is Hank?,ToshiCapital Rekordz Needs Help to Complete Album,Community Film Project: The Art of Neighborhoo...
category,Poetry,Narrative Film,Narrative Film,Music,Film & Video
main_category,Publishing,Film & Video,Film & Video,Music,Film & Video
currency,GBP,USD,USD,USD,USD
deadline,2015-10-09,2017-11-01,2013-02-26,2012-04-16,2015-08-29
goal,1000,30000,45000,5000,19500
launched,2015-08-11 12:12:28,2017-09-02 04:43:57,2013-01-12 00:20:50,2012-03-17 03:24:11,2015-07-04 08:35:03
pledged,0,2421,220,1,1283
state,failed,failed,failed,failed,canceled
backers,0,15,3,1,14
country,GB,US,US,US,US
usd pledged,0,100,220,1,1283
usd_pledged_real,0,2421,220,1,1283
usd_goal_real,1533.95,30000,45000,5000,19500

# Wine-Review-Datensatz

- Datensatz mit Weinbewertungen von der Plattform [WineEnthusiast](https://www.winemag.com/)
- ~130.000 Datensätze mit Weinbewertungen
- Metadaten wie:
    - Beschreibung des Sommeliers (blumig, erdig usw.)
    - Herkunftsland/-region
    - Winzer
    - Bewertung auf einer Punkteskala

In [17]:
import pandas
wine_reviews = pandas.read_csv(r'../datasets/wine-reviews/winemag-data_first150k.csv')
wine_reviews.head().transpose()

,0,1,2,3,4
Unnamed: 0,0,1,2,3,4
country,US,Spain,US,US,France
description,This tremendous 100% varietal wine hails from ...,"Ripe aromas of fig, blackberry and cassis are ...",Mac Watson honors the memory of a wine once ma...,"This spent 20 months in 30% new French oak, an...","This is the top wine from La Bégude, named aft..."
designation,Martha's Vineyard,Carodorum Selección Especial Reserva,Special Selected Late Harvest,Reserve,La Brûlade
points,96,96,96,96,95
price,235,110,90,65,66
province,California,Northern Spain,California,Oregon,Provence
region_1,Napa Valley,Toro,Knights Valley,Willamette Valley,Bandol
region_2,Napa,NaN,Sonoma,Willamette Valley,NaN
variety,Cabernet Sauvignon,Tinta de Toro,Sauvignon Blanc,Pinot Noir,Provence red blend
winery,Heitz,Bodega Carmen Rodríguez,Macauley,Ponzi,Domaine de la Bégude

# Aufgabe:

1. Importieren sie die .csv-Daten in ihr Jupyter Notebook
2. Verschaffen sie sich einen Überblick über den Datensatz
    - (`head()`, `describe()`, `sample(n)`)
3. Überlegen sie sich Hypothesen, die sie unterstützen möchten
4. Untersuchen sie die Hypothesen und visualisieren die Ergebnisse